# Generated by Django 4.2.1 on 2023-05-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_slide', models.ImageField(upload_to='slide_site/', verbose_name='Биринчи слайд')),
                ('second_slide', models.ImageField(upload_to='slide_site/', verbose_name='Второй слайд')),
                ('description_slide', models.TextField(verbose_name='Слайдка маалымат!')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайд',
                'ordering': ('id',),
            },
        ),
    ]
