# Generated by Django 4.2.1 on 2023-05-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0003_pride'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_school', models.CharField(max_length=255, verbose_name='МЕКТЕПТИН НЕГИЗДЕЛГЕН ЖЫЛЫ')),
                ('child_school', models.CharField(max_length=255, verbose_name='ОКУУЧУЛАРДЫН САНЫ')),
                ('graduate_school', models.CharField(max_length=255, verbose_name='БҮТҮРҮҮЧҮЛӨР (ЖЫЛЫНА)')),
                ('book_school', models.CharField(max_length=255, verbose_name='КИТЕПТЕРДИН САНЫ')),
            ],
            options={
                'verbose_name': 'Биз сандабыз!',
                'verbose_name_plural': 'Биз сандабыз!',
                'ordering': ('id',),
            },
        ),
    ]
