# Generated by Django 4.2.1 on 2023-05-19 10:11

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_settings_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Биз жонундо кыскача маалымат')),
                ('descriptions', models.TextField(verbose_name='Биз жонундо кененрээк маалымат')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality='100', scale=None, size=[1920, 1080], upload_to='about_image', verbose_name='Биз жонундо сурот')),
            ],
            options={
                'verbose_name': 'Биз жонундо',
                'verbose_name_plural': 'Биз жонундо',
            },
        ),
        migrations.AlterField(
            model_name='settings',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='logo/', verbose_name='Логотип'),
        ),
    ]
